openapi: 3.0.0
info:
  description: Add syncables to the A-Cube Peppol API.
actions:
- target: paths['/invoices/outgoing/ubl']['post']
  update:
    requestBody:
      content:
        application/xml:
          schema:
            type: string
        application/json:
          schema:
            type: string
- target: paths['/invoices']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      paginationStrategy: pageNumber
- target: paths['/credit-notes']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: creditNote
      description: |-
        Credit Notes received or sent by the authenticated user.
      type: collection