openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: components.schemas
  update:
    CreateWebhook:
      description: FIXME
    UpdateWebhook:
      description: FIXME
- target: paths['/orgs/{orgId}/transactions/to_network']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      itemsPathInResponse:
        - items
      paginationStrategy: pageToken
      pageTokenParam: lastEvaluatedKey # optional for first page, read from response for subsequent pages
      nextPageTokenPathInResponse:
       - pagination
       - lastEvaluatedKey
