openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/__tests__/integration/oad/arratech.yaml
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: components.schemas
  update:
    CreateWebhook:
      description: FIXME
    UpdateWebhook:
      description: FIXME
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: paths['/orgs/{orgId}/transactions/to_network']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      type: collection
- target: components
  update:
    paginationSchemes:
      default:
        paginate: items
        token:
          parameter: lastEvaluatedKey
