openapi: 3.0.0
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: paths['/three']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      paginationStrategy: pageNumber
      itemsPathInResponse:
      - news
      - you
      - posts
