openapi: 3.0.0
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: paths['/posts']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      description: |-
        Posts of the currently authenticated user.
      type: collection
      field: items
      pagingStrategy: pageToken
      pageTokenParam: nextPageToken # optional for first page, read from response for subsequent pages
