openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/__tests__/integration/oad/google-calendar.yaml
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: components
  update:
    paginationSchemes:
      default:
        paginate: items
        token:
          parameter: pageToken
          responseBody: nextPageToken