openapi: 3.0.0
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: paths['/users/me/calendarList']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      description: |-
        Calendars of the currently authenticated user.
      type: collection
      paginationStrategy: pageToken
      itemsPathInResponse:
        - items
