openapi: 3.0.0
actions:
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: paths['/api/v2/send-transactions']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      itemsPathInResponse:
      - results
      paginationStrategy: offset
