openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/__tests__/integration/oad/maventa.yaml
actions:
- target: paths['/v1/invoices']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      paginationStrategy: pageNumber
