openapi: 3.0.0
actions:
- target: paths['/v1/invoices']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      paginationStrategy: pageNumber
