openapi: 3.0.0
actions:
- target: paths['/documentsList']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      query:
        flow: out
      pagingStrategy: dateRange
      startDateParamInQuery: startDate
      endDateParamInQuery: endDate
