openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/__tests__/integration/oad/netfly.yaml
actions:
- target: paths['/documentsList']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      query:
        flow: out
      paginationStrategy: dateRange
      startDate: '20210101000000'
      endDate: '20250101000000'
      