openapi: 3.0.0
actions:
- target: paths['/message/list']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      paginationStrategy: pageNumber
      itemsPathInResponse:
      - items
