openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/__tests__/integration/oad/peppyrus.yaml
actions:
- target: paths['/message/list']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
- target: components
  update:
    paginationSchemes:
      default:
        paginate: items
        pageNumber:
          parameter: page
