openapi: 3.0.0
actions:
- target: paths['/message/list']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
      name: integrationTest
      pagingStrategy: pageNumber
      itemsPathInResponse:
      - items
