openapi: 3.0.0
actions:
- target: paths['/api/peppol/{teamId}/documents']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      itemsPathInResponse:
      - documents
      paginationStrategy: pageNumber
