openapi: 3.0.0
actions:
- target: paths['/v1/company/{companyID}/peppol/inbound/document/unconfirmed']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: integrationTest
      pagingStrategy: confirmationBased
      itemsPathInResponse:
      - results
      confirmOperation:
        path: /v1/company/{companyID}/peppol/inbound/document/{documentID}/confirm
        pathTemplate: /v1/company/{companyID}/peppol/inbound/document/{id}/confirm
        idField: id
        method: put
