openapi: 3.0.0
actions:
- target: paths['/v1/company/{companyID}/peppol/inbound/document/unconfirmed']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: integrationTest
      paginationStrategy: confirmationBased
      itemsPathInResponse:
      - results
      idField: id
      confirmOperation:
        path: /v1/company/{companyID}/peppol/inbound/document/{documentID}/confirm
        method: put
- target: paths['/v1/company/{companyID}/peppol/inbound/document/{documentID}/confirm']['put']['responses']['200']
  update:
    content:
      application/json:
        confirmOperation:
          pathTemplate: /v1/company/{companyID}/peppol/inbound/document/{id}/confirm
