openapi: 3.1.0
info:
  title: Blog API
  version: 1.0.0
servers:
  - url: 'http://localhost:3003'
    description: Local Mock Server
paths:
  /one:
    get:
      summary: List all posts
      operationId: listPosts
      x-handler: |
        return store.list('Post')
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
  /two:
    get:
      summary: List all posts
      operationId: listPosts
      x-handler: |
        return { posts: store.list('Post') };
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
  /three:
    get:
      summary: List all posts
      operationId: listPosts
      x-handler: |
        return { news: { you: { posts: store.list('Post') } } };
      responses:
        '200':
          description: List of posts
          content:
            application/json:
              schema:
                type: object
                properties:
                  news:
                    type: object
                    properties:
                      you:
                        type: object
                        properties:
                          posts:
                            type: array
                            items:
                              $ref: '#/components/schemas/Post'
components:
  schemas:
    Post:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        content:
          type: string
        author:
          type: string
        publishedAt:
          type: string
          format: date-time
        createdAt:
          type: string
          format: date-time
      x-seed: |
        seed.count(1, () => ({
          id: 'some-id',
          title: 'Some title',
          content: 'contents of the blogpost',
          author: 'Michiel de Jong',
          publishedAt: "2025-05-01T06:00:21.920Z",
          createdAt: "2025-05-01T06:00:21.920Z"
        }))