openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: $
  update:
    syncables:
      toNetwork:
        description: |-
          Invoice and Credit Note Documents sent by the authenticated user.
        type: collection
        get:
          path: /orgs/{orgId}/transactions/to_network
          field: items
          paging:
            pageTokenParam: lastEvaluatedKey # optional for first page, read from response for subsequent pages
            pageSizeParam: limit

      fromNetwork:
        description: |-
          Invoice and Credit Note Documents received by the authenticated user.
        type: collection
        get:
          path: /orgs/{orgId}/transactions/from_network
          field: items
          paging:
            pageTokenParam: lastEvaluatedKey # optional for first page, read from response for subsequent pages
            pageSizeParam: limit
