openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: components.schemas
  update:
    CreateWebhook:
      description: FIXME
    UpdateWebhook:
      description: FIXME
- target: components
  update:
    securitySchemes:
      cognito:
        type: cognito
        cognitoUrl: 'https://cognito-idp.eu-central-1.amazonaws.com/'
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: paths['/orgs/{orgId}/transactions/to_network']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: toNetwork
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      field: items
      paginationStrategy: pageToken
      pageTokenParam: lastEvaluatedKey # optional for first page, read from response for subsequent pages
- target: paths['/orgs/{orgId}/transactions/from_network']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: fromNetwork
      description: |-
        Invoice and Credit Note Documents received by the authenticated user.
      type: collection
      field: items
      paginationStrategy: pageToken
      pageTokenParam: lastEvaluatedKey # optional for first page, read from response for subsequent pages