openapi: 3.0.0
extends: https://raw.githubusercontent.com/APIs-guru/openapi-directory/refs/heads/main/APIs/github.com/api.github.com/1.1.4/openapi.yaml
actions:
- target: components
  update:
    securitySchemes:
      oauth2:
        type: oauth2
        flows:
          authorizationCode:
            authorizationUrl: https://github.com/login/oauth/authorize
            tokenUrl: https://github.com/login/oauth/access_token
            scopes:
              read:user:email: Grants read access to a user's email addresses.
# - target: paths['/repos/{owner}/{repo}/issues']['get']['responses']['200']['content']['application/json']
#   update:
#     syncables:
#     - name: issues
#       description: |-
#         Issues in the repository.
#       type: collection
#       query:
#         owner: tubsproject
#         repo: syncables
- target: components
  update:
    paginationSchemes:
      default:
        paginate: ''
        nextPageLink:
          responseHeader: Link
- target: components
  update:
    collections:
      /repos/{owner}/{repo}/issues:
        list: 'get /repos/{owner}/{repo}/issues'
        add: 'post /repos/{owner}/{repo}/issues'
