openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/openapi/oad/google-calendar.yaml
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: components
  update:
    paginationSchemes:
      default:
        paginate: items
        token:
          parameter: pageToken
          responseBody: nextPageToken
- target: components
  update:
    relations:
      parameters:
        calendarId: /users/me/calendarList#id
        setting: /users/me/settings#id