openapi: 3.0.0
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: $
  update:
    syncables:
      calendarList:
        description: |-
          Calendars of the currently authenticated user.
        type: collection
        schema:
        $ref: "#/components/schemas/CalendarListEntry"
        get:
          path: /users/me/calendarList
          operation: get
          field: items
        add:
          path: /users/me/calendarList
          operation: post