openapi: 3.0.0
info:
  description: Add syncables to the Google Calendar API.
actions:
- target: $
  update:
    syncables:
      calendarList:
        description: |-
          Calendars of the currently authenticated user.
        type: collection
        schema:
          $ref: "#/components/schemas/CalendarListEntry"
        list:
          path: /users/me/calendarList
          operation: get
          field: items
          paging:
            pageTokenParam: nextPageToken # optional for first page, read from response for subsequent pages
            syncTokenParam: nextSyncToken # keep polling after last page to get updates
            pageSizeParam: maxResults
        add:
          path: /users/me/calendarList
          operation: post