openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: $
  update:
    syncables:
      sendTransactions:
        description: |-
          Invoice and Credit Note Documents sent by the authenticated user.
        type: collection
        get:
          path: /api/v2/send-transactions
          field: results
      receiveTransactions:
        description: |-
          Invoice and Credit Note Documents received by the authenticated user.
        type: collection
        get:
          path: /api/v2/receive-transactions
          field: results