openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: paths['/api/v2/send-transactions']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: sendTransactions
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      field: results
      pagingStrategy: offset
      offsetParam: offset # optional for first page, multiple of limit for subsequent pages
- target: paths['/api/v2/receive-transactions']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: receiveTransactions
      description: |-
        Invoice and Credit Note Documents received by the authenticated user.
      type: collection
      field: results
      pagingStrategy: offset
      offsetParam: offset # optional for first page, multiple of limit for subsequent pages
