openapi: 3.0.0
info:
  description: Add syncables to the Moneybird API.
actions:
- target: paths['/administrations{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: administrations
      paginationStrategy: none
      query:
        format: .json

- target: paths['/{administration_id}/assets{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: assets
      paginationStrategy: pageNumber
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/contacts{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: contacts
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/contacts/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/document_styles{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: document_styles
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/general_documents{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: general_documents
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/general_documents/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/general_journal_documents{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: general_journal_documents
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/general_journal_documents/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/purchase_invoices{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: purchase_invoices
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/purchase_invoices/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/receipts{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: receipts
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/receipts/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/typeless_documents{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: typeless_documents
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/typeless_documents/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/downloads{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: downloads
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/estimates{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: estimates
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/estimates/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/documents/external_sales_invoices{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: external_sales_invoices
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/external_sales_invoices/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

# FIXME: Should we add /{administration_id}/external_sales_invoices/{external_sales_invoice_id}/attachments/{id}/download{format}?

- target: paths['/{administration_id}/financial_accounts{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: financial_accounts
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id


- target: paths['/{administration_id}/documents/financial_mutations{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: financial_mutations
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/documents/financial_mutations/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id


- target: paths['/{administration_id}/financial_statements{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: financial_statements
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/identities{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: identities
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id

# FIXME: should be storing these into the same db table with just a boolean field to indicate whether it's the default identity or not, but for now just storing them separately since it's faster to implement and we don't have support for multiple syncables using the same db table yet.
- target: paths['/{administration_id}/identities/default{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      type: item
      name: default_identities
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/ledger_accounts{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: ledger_accounts
      paginationStrategy: none
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/products{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: products
      paginationStrategy: pageNumber
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/projects{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: projects
      paginationStrategy: pageNumber
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/purchase_transactions{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: purchase_transactions
      paginationStrategy: pageNumber
      query:
        format: .json
      params:
        administration_id: administrations.id

- target: paths['/{administration_id}/recurring_sales_invoices{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: recurring_sales_invoices
      paginationStrategy: pageNumber
      synchronization: /{administration_id}/recurring_sales_invoices/synchronization{format}
      query:
        format: .json
      params:
        administration_id: administrations.id

# ...


# The Moneybird spec says identifiers can be strings or integers. What it really means is that
# it is a stringified integer. We don't have support for that (yet) so overriding it here to just string.
- target: components.schemas.identifier
  update:
    type: string
    commment: Moneybird identifiers are stringified integers, so we can just treat them as strings.

# This should be covered by the previous edit, but our code can't deal with $ref inside allOf,
# so need to do it manually here for now. We can add support for $ref inside allOf later, but this is faster to implement for now.:
- target: components.schemas
  update:
    administration_id:
      type: string
- target: components.schemas.administration_id.allOf
  remove: true
