openapi: 3.0.0
info:
  description: Add syncables to the Moneybird API.
actions:
- target: paths['/administrations{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: administrations
      paginationStrategy: none
      query:
        format: .json
- target: components.schemas
  update:
    administration_id:
      type: string
- target: components.schemas.administration_id.allOf
  remove: true
- target: paths['/{administration_id}/assets{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: assets
      paginationStrategy: pageNumber
      query:
        format: .json
      params:
        administration_id: administrations.id
- target: paths['/{administration_id}/contacts{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: contacts
      paginationStrategy: pageNumber
      query:
        format: .json
      params:
        administration_id: administrations.id
- target: components.schemas.base_contact_response.properties
  update:
    id:
      type: string
- target: components.schemas.base_contact_response.properties.id['$ref']
  remove: true
