openapi: 3.0.0
info:
  description: Add syncables to the Moneybird API.
actions:
- target: paths['/administrations{format}']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: administrations
      paginationStrategy: none
      query:
        format: .json
- target: components.schemas
  update:
    administration_id:
      type: string
- target: components.schemas.administration_id.allOf
  remove: true