openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: paths['/documentsList']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: documentsOut
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      query:
        flow: out
      pagingStrategy: dateRange
      startDateParamInQuery: startDate
      endDateParamInQuery: endDate
- target: paths['/documentsList']['get']['responses']['200']['content']['application/json']
  update:
    syncable:
      name: documentsOut
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      query:
        flow: in
      pagingStrategy: dateRange
      startDate: '20210101000000' // YYYYMMDDHHMMSS
      endDate: '20250101000000' // YYYYMMDDHHMMSS
      