openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: $
  update:
    servers:
    - url: https://test.ion-ap.net
- target: $
  update:
    syncables:
      documents:
        description: |-
          Invoice and Credit Note Documents sent by the authenticated user.
        type: collection
        list:
          path: /documentsList
          method: get
        paging:
          startDateParam: startDate
          endDateParam: endDate
        add-doc:
          path: /sendDocument
          method: post
        get-doc:
          path: /receiveDocument
          method: get