openapi: 3.0.0
info:
  description: Add syncables to the Ion Peppol API.
actions:
- target: components.securitySchemes
  update:
    oauth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: 'https://netfly-test.eu.auth0.com/oauth/token'
          audience: 'https://netfly-test.eu.auth0.com/api/v2/'

- target: paths['/documentsList']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
      name: documentsOut
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      query:
        flow: out
      paginationStrategy: dateRange
      startDateParamInQuery: startDate
      endDateParamInQuery: endDate
- target: paths['/documentsList']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: documentsIn
      description: |-
        Invoice and Credit Note Documents sent by the authenticated user.
      type: collection
      query:
        flow: in
      paginationStrategy: dateRange
      startDate: '20210101000000' // YYYYMMDDHHMMSS
      endDate: '20250101000000' // YYYYMMDDHHMMSS
      