openapi: 3.0.0
actions:
- target: components
  update:
    securitySchemes:
      oauth2:
        type: oauth2
        flows:
          authorizationCode:
            authorizationUrl: https://slack.com/oauth/v2/authorize
            tokenUrl: https://slack.com/api/oauth.v2.access
            scopes:
              users:read.email: Grants read access to a user's profile information and presence status.
- target: paths['/conversations.list']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: conversations
      type: collection
      paginationStrategy: pageToken
      pageTokenPathInResponse: response_metadata.next_cursor
