openapi: 3.0.0
extends: https://raw.githubusercontent.com/tubsproject/syncables/refs/tags/v0.14.0/openapi/oad/slack-web.yaml
actions:
- target: components.securitySchemes.slackAuth.flows.authorizationCode
  update:
    scopes:
      users:read.email: Grants read access to a user's profile information and presence status.
- target: paths['/conversations.list']['get']['responses']['200']['content']['application/json']
  update:
    syncables:
    - name: conversations
      type: collection
      paginationStrategy: pageToken
      pageTokenPathInResponse: response_metadata.next_cursor
